=== Laurcons/cs-lftc3-lab3/fa_parser/src/fa-examples/fa.schema.json
{
  "$ref": "#/definitions/IFAConfig",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "IFAConfig": {
      "properties": {
        "finalStates": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "initialState": {
          "type": "string"
        },
        "states": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "transitions": {
          "items": {
            "$ref": "#/definitions/ITransition"
          },
          "type": "array"
        }
      },
      "required": [
        "states",
        "initialState",
        "finalStates",
        "transitions"
      ],
      "type": "object"
    },
    "ITransition": {
      "anyOf": [
        {
          "properties": {
            "from": {
              "type": "string"
            },
            "isSpecial": {
              "const": false,
              "type": "boolean"
            },
            "to": {
              "type": "string"
            },
            "via": {
              "type": "string"
            }
          },
          "required": [
            "from",
            "to",
            "via"
          ],
          "type": "object"
        },
        {
          "properties": {
            "except": {
              "type": "string"
            },
            "from": {
              "type": "string"
            },
            "isSpecial": {
              "const": true,
              "type": "boolean"
            },
            "to": {
              "type": "string"
            },
            "via": {
              "const": "anyOneUnicode",
              "type": "string"
            }
          },
          "required": [
            "from",
            "isSpecial",
            "to",
            "via"
          ],
          "type": "object"
        }
      ]
    }
  }
}

=== Laurcons/cs-lftc3-lab3/fa_parser/fa-examples/iakabscriptlite-integer-literal.json
{
  "$schema": "./fa.schema.json",
  "states": ["q", "r"],
  "initialState": "q",
  "finalStates": ["r"],
  "transitions": [
    { "from": "q", "to": "r", "via": "0" },
    { "from": "q", "to": "r", "via": "1" },
    { "from": "q", "to": "r", "via": "2" },
    { "from": "q", "to": "r", "via": "3" },
    { "from": "q", "to": "r", "via": "4" },
    { "from": "q", "to": "r", "via": "5" },
    { "from": "q", "to": "r", "via": "6" },
    { "from": "q", "to": "r", "via": "7" },
    { "from": "q", "to": "r", "via": "8" },
    { "from": "q", "to": "r", "via": "9" },

    { "from": "r", "to": "r", "via": "0" },
    { "from": "r", "to": "r", "via": "1" },
    { "from": "r", "to": "r", "via": "2" },
    { "from": "r", "to": "r", "via": "3" },
    { "from": "r", "to": "r", "via": "4" },
    { "from": "r", "to": "r", "via": "5" },
    { "from": "r", "to": "r", "via": "6" },
    { "from": "r", "to": "r", "via": "7" },
    { "from": "r", "to": "r", "via": "8" },
    { "from": "r", "to": "r", "via": "9" }
  ]
}

=== Laurcons/cs-lftc3-lab3/fa_parser/fa-examples/iakabscriptlite-string-literal.json
{
  "$schema": "./fa.schema.json",
  "states": ["q", "r", "s"],
  "initialState": "q",
  "finalStates": ["s"],
  "transitions": [
    { "from": "q", "to": "r", "via": "„" },
    {
      "from": "r",
      "to": "r",
      "isSpecial": true,
      "via": "anyOneUnicode",
      "except": "”"
    },
    { "from": "r", "to": "s", "via": "”" }
  ]
}
